apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ClusterImagePolicy
metadata:
  name: no-vulnerable-images
spec:
  repositories:
    - name: us.icr.io/<my_namespace>/*
      policy:
        va:
          enabled: true
